#!/usr/bin/env python3
"""
h2_to_postgres.py
-----------------
Converts a Gameyfin H2 database export (produced by org.h2.tools.Script)
into a PostgreSQL-compatible SQL file, ready to import via pgAdmin.

Usage:
    python3 h2_to_postgres.py <input_export.sql> <output_postgres.sql>

Example:
    python3 h2_to_postgres.py export.sql gameyfin_postgres.sql

To produce the H2 export in the first place (stop Gameyfin first!):
    docker run --rm \\
      -v /path/to/gameyfin/db:/db \\
      eclipse-temurin:25-jdk-jammy bash -c "
        apt-get update -qq && apt-get install -y -qq curl &&
        curl -sL https://repo1.maven.org/maven2/com/h2database/h2/2.3.232/h2-2.3.232.jar -o /tmp/h2.jar &&
        java -cp /tmp/h2.jar org.h2.tools.Script \\
          -url 'jdbc:h2:file:/db/gameyfin_db;AUTO_SERVER=FALSE' \\
          -user gfadmin \\
          -password gameyfin \\
          -script /db/export.sql
      "
"""

import re
import sys
import os


# ── Helpers ───────────────────────────────────────────────────────────────────

def decode_h2_unicode(s):
    """Decode H2 U&'...' unicode escapes like \\2019 -> ' """
    return re.sub(r'\\([0-9a-fA-F]{4})', lambda m: chr(int(m.group(1), 16)), s)


def pg_escape(s):
    """Escape single quotes for PostgreSQL string literals."""
    return s.replace("'", "''")


# ── Step 1: Extract SYSTEM_LOB_STREAM data ────────────────────────────────────

def extract_lobs(content):
    """
    Parse all SYSTEM_LOB_STREAM rows and return a dict of {lob_id: combined_text}.
    H2 splits large CLOBs across multiple parts; we reassemble them here.
    """
    pattern = re.compile(
        r"INSERT INTO SYSTEM_LOB_STREAM VALUES\("
        r"(\d+),\s*(\d+),\s*"
        r"(U&'(?:[^']|'')*'|'(?:[^']|'')*'|NULL)"
        r",\s*(NULL|[^\)]+)\)"
    )

    lobs = {}
    for m in pattern.finditer(content):
        lob_id = int(m.group(1))
        part   = int(m.group(2))
        cdata  = m.group(3)

        if cdata == 'NULL':
            text = ''
        elif cdata.startswith("U&'"):
            text = decode_h2_unicode(cdata[3:-1])
        else:
            text = cdata[1:-1]

        text = text.replace("''", "'")
        lobs.setdefault(lob_id, {})[part] = text

    return {
        lob_id: ''.join(parts[p] for p in sorted(parts.keys()))
        for lob_id, parts in lobs.items()
    }


# ── Step 2: Line-by-line conversion ───────────────────────────────────────────

SKIP_PATTERNS = [
    re.compile(r'^\s*SET\s+CACHE_SIZE', re.IGNORECASE),
    re.compile(r'^\s*CREATE\s+(FORCE\s+)?ALIAS', re.IGNORECASE),
    re.compile(r'^\s*DROP\s+ALIAS', re.IGNORECASE),
    re.compile(r'^\s*CREATE\s+(CACHED\s+LOCAL\s+TEMPORARY|MEMORY)\s+TABLE.*SYSTEM_LOB_STREAM', re.IGNORECASE),
    re.compile(r'^\s*ALTER\s+TABLE\s+SYSTEM_LOB_STREAM', re.IGNORECASE),
    re.compile(r'^\s*INSERT\s+INTO\s+SYSTEM_LOB_STREAM', re.IGNORECASE),
    re.compile(r'^\s*DROP\s+TABLE\s+IF\s+EXISTS\s+SYSTEM_LOB_STREAM', re.IGNORECASE),
    re.compile(r'^\s*CREATE\s+USER\s+IF\s+NOT\s+EXISTS', re.IGNORECASE),
]


def make_clob_replacer(combined_lobs):
    def replace_clob(m):
        idx  = int(m.group(1))
        text = combined_lobs.get(idx, '')
        return f"'{pg_escape(text)}'"
    return replace_clob


def convert_sequence(m):
    """
    H2: CREATE SEQUENCE "X" START WITH 1 RESTART WITH N INCREMENT BY 50
    PG: CREATE SEQUENCE x INCREMENT BY 50 START WITH N MINVALUE 1 NO MAXVALUE CACHE 1
    Uses RESTART value as START so the counter resumes at the right position.
    Name is lowercased and unquoted.
    """
    name      = m.group(1).strip('"').lower()
    restart   = m.group(2)
    increment = m.group(3)
    return (
        f'CREATE SEQUENCE {name}\n'
        f'    INCREMENT BY {increment}\n'
        f'    START WITH {restart}\n'
        f'    MINVALUE 1\n'
        f'    NO MAXVALUE\n'
        f'    CACHE 1'
    )


def convert_identity(m):
    """
    H2: GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH N)
    PG: GENERATED BY DEFAULT AS IDENTITY (START WITH N)
    """
    return f'GENERATED BY DEFAULT AS IDENTITY (START WITH {m.group(1)})'


def fix_hex_literal(m):
    """X'hexdata' -> '\\xhexdata'  (PostgreSQL bytea hex format)"""
    return f"'\\x{m.group(1)}'"


def fix_unicode_string(m):
    """U&'...' -> '...'  (decode H2 unicode escapes to plain text)"""
    inner = decode_h2_unicode(m.group(1))
    inner = inner.replace("'", "''")
    return f"'{inner}'"


def lowercase_quoted_identifiers(line):
    """
    Convert all "UPPER_CASE" quoted identifiers to unquoted lower_case.
    e.g. "GAME" -> game,  "LIBRARY_ID" -> library_id
    Leaves mixed-case or already-lowercase quoted identifiers alone
    (e.g. "key", "value" which are intentionally quoted reserved words).
    """
    def replacer(m):
        name = m.group(1)
        if name == name.upper():
            return name.lower()
        return f'"{name}"'
    return re.sub(r'"([A-Za-z][A-Za-z0-9_]*)"', replacer, line)


def convert(content, combined_lobs):
    clob_replacer = make_clob_replacer(combined_lobs)
    lines = content.split('\n')
    out   = []

    for line in lines:
        stripped = line.strip()

        # Drop H2-only lines
        if any(p.match(stripped) for p in SKIP_PATTERNS):
            continue

        # Inline CLOB data
        line = re.sub(r'SYSTEM_COMBINE_CLOB\((\d+)\)', clob_replacer, line)

        # ── Type mappings ──────────────────────────────────────────────────
        line = re.sub(r'\bTINYINT\b',                'SMALLINT', line)
        line = re.sub(r'\bBINARY VARYING\(\d+\)',     'BYTEA',    line)
        line = re.sub(r'\bCHARACTER LARGE OBJECT\b',  'TEXT',     line)
        line = re.sub(r'\bCLOB\b',                    'TEXT',     line)
        line = re.sub(
            r"\bENUM\s*\('ADMIN',\s*'SUPERADMIN',\s*'USER'\)",
            'VARCHAR(255)', line
        )

        # ── DDL fixes ──────────────────────────────────────────────────────
        line = re.sub(r'\bCREATE CACHED TABLE\b',                'CREATE TABLE',       line, flags=re.IGNORECASE)
        line = re.sub(r'\bCREATE UNIQUE NULLS DISTINCT INDEX\b', 'CREATE UNIQUE INDEX', line, flags=re.IGNORECASE)
        line = re.sub(r'\bUNIQUE NULLS DISTINCT\b',              'UNIQUE',             line, flags=re.IGNORECASE)
        line = re.sub(r'\s+NULLS FIRST\b',                       '',                   line)
        line = re.sub(r'\s+NULLS LAST\b',                        '',                   line)
        line = re.sub(r'\s+NOCHECK\b',                           '',                   line)
        line = re.sub(r'\s+SELECTIVITY\s+\d+',                   '',                   line)

        # Remove "PUBLIC". schema prefix
        line = re.sub(r'"PUBLIC"\.', '', line)

        # ── Sequence syntax ────────────────────────────────────────────────
        line = re.sub(
            r'CREATE SEQUENCE ("[^"]+")\s+START WITH \d+\s+RESTART WITH (\d+)\s+INCREMENT BY (\d+)',
            convert_sequence, line
        )

        # ── IDENTITY column ────────────────────────────────────────────────
        line = re.sub(
            r'GENERATED BY DEFAULT AS IDENTITY\(START WITH \d+ RESTART WITH (\d+)\)',
            convert_identity, line
        )

        # ── Binary / unicode data ──────────────────────────────────────────
        line = re.sub(r"\bX'([0-9a-fA-F]+)'", fix_hex_literal,    line)
        line = re.sub(r"U&'((?:[^']|'')*)'",   fix_unicode_string, line)

        # ── Lowercase all quoted UPPERCASE identifiers ─────────────────────
        # Tables, columns, constraints, indexes — must come last
        line = lowercase_quoted_identifiers(line)

        out.append(line)

    return '\n'.join(out)


# ── Step 3: Sanity check ──────────────────────────────────────────────────────

H2_TERMS = [
    'SYSTEM_COMBINE_CLOB', 'CREATE FORCE ALIAS', 'CREATE CACHED TABLE',
    'TINYINT', 'BINARY VARYING', 'CHARACTER LARGE OBJECT',
    'SET CACHE_SIZE', 'SYSTEM_LOB_STREAM', '"PUBLIC".',
    'NULLS DISTINCT', 'NULLS FIRST', 'NOCHECK', 'SELECTIVITY',
    'CREATE USER IF NOT EXISTS', 'RESTART WITH',
]

def sanity_check(content):
    issues = [(t, content.count(t)) for t in H2_TERMS if content.count(t) > 0]
    if issues:
        print("⚠  Remaining H2-specific terms:")
        for term, count in issues:
            print(f"   {term}: {count} occurrence(s)")
    else:
        print("✓  No H2-specific syntax remaining")

    upper_quoted = re.findall(r'"([A-Z][A-Z0-9_]{2,})"', content)
    if upper_quoted:
        unique = sorted(set(upper_quoted))
        print(f"⚠  Remaining uppercase quoted identifiers ({len(unique)}): {unique[:10]}{'...' if len(unique) > 10 else ''}")
    else:
        print("✓  No uppercase quoted identifiers remaining")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    input_path  = sys.argv[1]
    output_path = sys.argv[2]

    if not os.path.exists(input_path):
        print(f"Error: input file not found: {input_path}")
        sys.exit(1)

    print(f"Reading {input_path} ...")
    with open(input_path, 'r', encoding='utf-8') as f:
        content = f.read()

    print("Extracting LOB data ...")
    combined_lobs = extract_lobs(content)
    print(f"  Found {len(combined_lobs)} LOB object(s)")

    print("Converting ...")
    result = convert(content, combined_lobs)

    print("Sanity check ...")
    sanity_check(result)

    print(f"Writing {output_path} ...")
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(result)

    print(f"Done! {content.count(chr(10)):,} input lines → {result.count(chr(10)):,} output lines")


if __name__ == '__main__':
    main()